// Posts
export const POSTS_FETCH_DATA_REJECT = 'POSTS_FETCH_DATA_REJECT';
export const POSTS_FETCH_DATA_REQUEST = 'POSTS_FETCH_DATA_REQUEST';
export const POSTS_FETCH_DATA_SUCCESS = 'POSTS_FETCH_DATA_SUCCESS';
export const POSTS_LOAD_MORE = 'POSTS_LOAD_MORE';
export const POSTS_RESET_LIMIT = 'POSTS_RESET_LIMIT';
export const FIND_POSTS = 'FIND_POSTS';

// Actors
export const ACTORS_FETCH_DATA_REJECT = 'ACTORS_FETCH_DATA_REJECT';
export const ACTORS_FETCH_DATA_REQUEST = 'ACTORS_FETCH_DATA_REQUEST';
export const ACTORS_FETCH_DATA_SUCCESS = 'ACTORS_FETCH_DATA_SUCCESS';
export const ACTORS_SET_VISIBILITY_FILTER = 'ACTORS_SET_VISIBILITY_FILTER';

// NavBar menu
export const NAVBAR_TOGGLE_MENU = 'NAVBAR_TOGGLE_MENU';

// Slider
export const SLIDER_FETCH_DATA_REJECT = 'SLIDER_FETCH_DATA_REJECT';
export const SLIDER_FETCH_DATA_REQUEST = 'SLIDER_FETCH_DATA_REQUEST';
export const SLIDER_FETCH_DATA_SUCCESS = 'SLIDER_FETCH_DATA_SUCCESS';
export const SLIDER_DOT_CLICK = 'SLIDER_DOT_CLICK';
export const SLIDER_TOGGLE_AUTOPLAY = 'SLIDER_TOGGLE_AUTOPLAY';
export const SLIDER_NEXT_SLIDE = 'SLIDER_NEXT_SLIDE';
export const SLIDER_PREV_SLIDE = 'SLIDER_PREV_SLIDE';
export const SLIDER_TOGGLE_INTERVAL = 'SLIDER_TOGGLE_INTERVAL';
