// Posts
export const POSTS_FETCH_DATA_REJECT = 'POSTS_FETCH_DATA_REJECT';
export const POSTS_FETCH_DATA_REQUEST = 'POSTS_FETCH_DATA_REQUEST';
export const POSTS_FETCH_DATA_SUCCESS = 'POSTS_FETCH_DATA_SUCCESS';
export const POSTS_LOAD_MORE = 'POSTS_LOAD_MORE';
export const POSTS_RESET_LIMIT = 'POSTS_RESET_LIMIT';
export const FIND_POSTS = 'FIND_POSTS';

// Actors
export const ACTORS_FETCH_DATA_REJECT = 'ACTORS_FETCH_DATA_REJECT';
export const ACTORS_FETCH_DATA_REQUEST = 'ACTORS_FETCH_DATA_REQUEST';
export const ACTORS_FETCH_DATA_SUCCESS = 'ACTORS_FETCH_DATA_SUCCESS';
export const ACTORS_SET_VISIBILITY_FILTER = 'ACTORS_SET_VISIBILITY_FILTER';

// NavBar menu
export const NAVBAR_TOGGLE_MENU = 'NAVBAR_TOGGLE_MENU';
