// Posts
export const POSTS_HAS_ERRORED = 'POSTS_HAS_ERRORED';
export const POSTS_IS_LOADING = 'POSTS_IS_LOADING';
export const POSTS_FETCH_DATA_SUCCESS = 'POSTS_FETCH_DATA_SUCCESS';

// Actors
export const ACTORS_HAS_ERRORED = 'ACTORS_HAS_ERRORED';
export const ACTORS_IS_LOADING = 'ACTORS_IS_LOADING';
export const ACTORS_FETCH_DATA_SUCCESS = 'ACTORS_FETCH_DATA_SUCCESS';
